In [1]:
import numpy as np

In [2]:
list = [1,2,3]
arr = np.array(list)

In [3]:
arr

array([1, 2, 3])

In [4]:
arr.ndim

1

In [5]:
list1 = [[1,2,3],[4,5,6]]

In [6]:
arr2 = np.array(list1)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.ndim

2

In [8]:
list2 = [[1,2,3],[4,5,6],[8,9,10],[11,12,13,]]

In [9]:
arr3 = np.array(list2)
arr3.shape
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [10]:
arr3[1:4]

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [14]:
arr3[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [12, 13]])

# Numpy inbuild methods

In [20]:
zeros = np.zeros((3,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
eye = np.eye(4,5)

In [24]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [26]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [27]:
np.linspace(100,200,20)

array([100.        , 105.26315789, 110.52631579, 115.78947368,
       121.05263158, 126.31578947, 131.57894737, 136.84210526,
       142.10526316, 147.36842105, 152.63157895, 157.89473684,
       163.15789474, 168.42105263, 173.68421053, 178.94736842,
       184.21052632, 189.47368421, 194.73684211, 200.        ])

In [28]:
np.random.rand(3,5)

array([[0.29910691, 0.00956334, 0.03876743, 0.8624968 , 0.12916045],
       [0.18433235, 0.86261657, 0.4207234 , 0.5657451 , 0.20376782],
       [0.4221946 , 0.73801481, 0.21294181, 0.89153189, 0.56141497]])

In [30]:
a = np.random.randint(10,30,15)
a

array([19, 10, 22, 13, 23, 12, 11, 15, 14, 28, 11, 15, 14, 14, 12])

In [31]:
b = a.reshape(5,3)
b

array([[19, 10, 22],
       [13, 23, 12],
       [11, 15, 14],
       [28, 11, 15],
       [14, 14, 12]])

In [32]:
c = np.random.randint(30,50,15).reshape(5,3)
c

array([[42, 45, 30],
       [44, 42, 49],
       [43, 35, 34],
       [41, 34, 34],
       [33, 33, 31]])

In [33]:
b+c

array([[61, 55, 52],
       [57, 65, 61],
       [54, 50, 48],
       [69, 45, 49],
       [47, 47, 43]])

In [35]:
con = np.concatenate((b,c),axis = 1)
con

array([[19, 10, 22, 42, 45, 30],
       [13, 23, 12, 44, 42, 49],
       [11, 15, 14, 43, 35, 34],
       [28, 11, 15, 41, 34, 34],
       [14, 14, 12, 33, 33, 31]])

In [36]:
np.delete(con, [2,4], axis = 0)

array([[19, 10, 22, 42, 45, 30],
       [13, 23, 12, 44, 42, 49],
       [28, 11, 15, 41, 34, 34]])